// Autogenerated by Thrift Compiler (0.9.3)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
	"Services/AuctionService"
	"flag"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
	"math"
	"net"
	"net/url"
	"os"
	"strconv"
	"strings"
)

func Usage() {
	fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
	flag.PrintDefaults()
	fmt.Fprintln(os.Stderr, "\nFunctions:")
	fmt.Fprintln(os.Stderr, "  BiddingMsg bidding(i64 dealerId, i64 orderId, double basePrice, double addPrice, i32 deviceType)")
	fmt.Fprintln(os.Stderr, "  BidMsg bid(i64 dealerId, i64 orderId, double price, i32 deviceType)")
	fmt.Fprintln(os.Stderr, "  bool intelBidSet(i64 dealerId, i64 orderId)")
	fmt.Fprintln(os.Stderr, "  bool intelBidStop(i64 dealerId, i64 orderId)")
	fmt.Fprintln(os.Stderr, "  bool intelBidding(i64 dealerId, i64 orderId, double basePrice, double addPrice)")
	fmt.Fprintln(os.Stderr)
	os.Exit(0)
}

func main() {
	flag.Usage = Usage
	var host string
	var port int
	var protocol string
	var urlString string
	var framed bool
	var useHttp bool
	var parsedUrl url.URL
	var trans thrift.TTransport
	_ = strconv.Atoi
	_ = math.Abs
	flag.Usage = Usage
	flag.StringVar(&host, "h", "localhost", "Specify host and port")
	flag.IntVar(&port, "p", 9090, "Specify port")
	flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
	flag.StringVar(&urlString, "u", "", "Specify the url")
	flag.BoolVar(&framed, "framed", false, "Use framed transport")
	flag.BoolVar(&useHttp, "http", false, "Use http")
	flag.Parse()

	if len(urlString) > 0 {
		parsedUrl, err := url.Parse(urlString)
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
		host = parsedUrl.Host
		useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
	} else if useHttp {
		_, err := url.Parse(fmt.Sprint("http://", host, ":", port))
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
	}

	cmd := flag.Arg(0)
	var err error
	if useHttp {
		trans, err = thrift.NewTHttpClient(parsedUrl.String())
	} else {
		portStr := fmt.Sprint(port)
		if strings.Contains(host, ":") {
			host, portStr, err = net.SplitHostPort(host)
			if err != nil {
				fmt.Fprintln(os.Stderr, "error with host:", err)
				os.Exit(1)
			}
		}
		trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
		if err != nil {
			fmt.Fprintln(os.Stderr, "error resolving address:", err)
			os.Exit(1)
		}
		if framed {
			trans = thrift.NewTFramedTransport(trans)
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error creating transport", err)
		os.Exit(1)
	}
	defer trans.Close()
	var protocolFactory thrift.TProtocolFactory
	switch protocol {
	case "compact":
		protocolFactory = thrift.NewTCompactProtocolFactory()
		break
	case "simplejson":
		protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
		break
	case "json":
		protocolFactory = thrift.NewTJSONProtocolFactory()
		break
	case "binary", "":
		protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
		Usage()
		os.Exit(1)
	}
	client := AuctionService.NewAuctionServiceClientFactory(trans, protocolFactory)
	if err := trans.Open(); err != nil {
		fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
		os.Exit(1)
	}

	switch cmd {
	case "bidding":
		if flag.NArg()-1 != 5 {
			fmt.Fprintln(os.Stderr, "Bidding requires 5 args")
			flag.Usage()
		}
		argvalue0, err12 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err12 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		argvalue1, err13 := (strconv.ParseInt(flag.Arg(2), 10, 64))
		if err13 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		argvalue2, err14 := (strconv.ParseFloat(flag.Arg(3), 64))
		if err14 != nil {
			Usage()
			return
		}
		value2 := argvalue2
		argvalue3, err15 := (strconv.ParseFloat(flag.Arg(4), 64))
		if err15 != nil {
			Usage()
			return
		}
		value3 := argvalue3
		tmp4, err16 := (strconv.Atoi(flag.Arg(5)))
		if err16 != nil {
			Usage()
			return
		}
		argvalue4 := int32(tmp4)
		value4 := argvalue4
		fmt.Print(client.Bidding(value0, value1, value2, value3, value4))
		fmt.Print("\n")
		break
	case "bid":
		if flag.NArg()-1 != 4 {
			fmt.Fprintln(os.Stderr, "Bid requires 4 args")
			flag.Usage()
		}
		argvalue0, err17 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err17 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		argvalue1, err18 := (strconv.ParseInt(flag.Arg(2), 10, 64))
		if err18 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		argvalue2, err19 := (strconv.ParseFloat(flag.Arg(3), 64))
		if err19 != nil {
			Usage()
			return
		}
		value2 := argvalue2
		tmp3, err20 := (strconv.Atoi(flag.Arg(4)))
		if err20 != nil {
			Usage()
			return
		}
		argvalue3 := int32(tmp3)
		value3 := argvalue3
		fmt.Print(client.Bid(value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "intelBidSet":
		if flag.NArg()-1 != 2 {
			fmt.Fprintln(os.Stderr, "IntelBidSet requires 2 args")
			flag.Usage()
		}
		argvalue0, err21 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err21 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		argvalue1, err22 := (strconv.ParseInt(flag.Arg(2), 10, 64))
		if err22 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		fmt.Print(client.IntelBidSet(value0, value1))
		fmt.Print("\n")
		break
	case "intelBidStop":
		if flag.NArg()-1 != 2 {
			fmt.Fprintln(os.Stderr, "IntelBidStop requires 2 args")
			flag.Usage()
		}
		argvalue0, err23 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err23 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		argvalue1, err24 := (strconv.ParseInt(flag.Arg(2), 10, 64))
		if err24 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		fmt.Print(client.IntelBidStop(value0, value1))
		fmt.Print("\n")
		break
	case "intelBidding":
		if flag.NArg()-1 != 4 {
			fmt.Fprintln(os.Stderr, "IntelBidding requires 4 args")
			flag.Usage()
		}
		argvalue0, err25 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err25 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		argvalue1, err26 := (strconv.ParseInt(flag.Arg(2), 10, 64))
		if err26 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		argvalue2, err27 := (strconv.ParseFloat(flag.Arg(3), 64))
		if err27 != nil {
			Usage()
			return
		}
		value2 := argvalue2
		argvalue3, err28 := (strconv.ParseFloat(flag.Arg(4), 64))
		if err28 != nil {
			Usage()
			return
		}
		value3 := argvalue3
		fmt.Print(client.IntelBidding(value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "":
		Usage()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
	}
}
