// Autogenerated by Thrift Compiler (0.9.3)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
	"gen-go/Services/BailService"
	"flag"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
	"math"
	"net"
	"net/url"
	"os"
	"strconv"
	"strings"
)

func Usage() {
	fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
	flag.PrintDefaults()
	fmt.Fprintln(os.Stderr, "\nFunctions:")
	fmt.Fprintln(os.Stderr, "  Bail getDealerBail(i64 dealerId)")
	fmt.Fprintln(os.Stderr, "  Bail freezeBail(i64 dealerId, double amount, i64 orderId)")
	fmt.Fprintln(os.Stderr, "  Bail unfreezeBail(i64 dealerId, i64 orderId)")
	fmt.Fprintln(os.Stderr, "  Bail decBail(i64 dealerId, double amount, i32 useType, string useDetail, i64 orderId, i32 rechargeMethod, i64 payMentId, i64 collectionId)")
	fmt.Fprintln(os.Stderr, "  Bail incBail(i64 dealerId, double amount, string useDetail, string rechargeNo, i64 rechargeId, i32 rechargeMethod, i32 collectionId)")
	fmt.Fprintln(os.Stderr, "  Bail unfreezeDecBail(i64 dealerId, i64 orderId, double decAmount, i32 useType, string useDetail)")
	fmt.Fprintln(os.Stderr, "  Bail getBailLogsByDealerId(i64 dealerId, i32 useType, string useTime, i32 page, i32 pageSize, i32 isUnFree, i32 payMethod)")
	fmt.Fprintln(os.Stderr)
	os.Exit(0)
}

func main() {
	flag.Usage = Usage
	var host string
	var port int
	var protocol string
	var urlString string
	var framed bool
	var useHttp bool
	var parsedUrl url.URL
	var trans thrift.TTransport
	_ = strconv.Atoi
	_ = math.Abs
	flag.Usage = Usage
	flag.StringVar(&host, "h", "localhost", "Specify host and port")
	flag.IntVar(&port, "p", 9090, "Specify port")
	flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
	flag.StringVar(&urlString, "u", "", "Specify the url")
	flag.BoolVar(&framed, "framed", false, "Use framed transport")
	flag.BoolVar(&useHttp, "http", false, "Use http")
	flag.Parse()

	if len(urlString) > 0 {
		parsedUrl, err := url.Parse(urlString)
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
		host = parsedUrl.Host
		useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
	} else if useHttp {
		_, err := url.Parse(fmt.Sprint("http://", host, ":", port))
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
	}

	cmd := flag.Arg(0)
	var err error
	if useHttp {
		trans, err = thrift.NewTHttpClient(parsedUrl.String())
	} else {
		portStr := fmt.Sprint(port)
		if strings.Contains(host, ":") {
			host, portStr, err = net.SplitHostPort(host)
			if err != nil {
				fmt.Fprintln(os.Stderr, "error with host:", err)
				os.Exit(1)
			}
		}
		trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
		if err != nil {
			fmt.Fprintln(os.Stderr, "error resolving address:", err)
			os.Exit(1)
		}
		if framed {
			trans = thrift.NewTFramedTransport(trans)
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error creating transport", err)
		os.Exit(1)
	}
	defer trans.Close()
	var protocolFactory thrift.TProtocolFactory
	switch protocol {
	case "compact":
		protocolFactory = thrift.NewTCompactProtocolFactory()
		break
	case "simplejson":
		protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
		break
	case "json":
		protocolFactory = thrift.NewTJSONProtocolFactory()
		break
	case "binary", "":
		protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
		Usage()
		os.Exit(1)
	}
	client := BailService.NewBailServiceClientFactory(trans, protocolFactory)
	if err := trans.Open(); err != nil {
		fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
		os.Exit(1)
	}

	switch cmd {
	case "getDealerBail":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetDealerBail requires 1 args")
			flag.Usage()
		}
		argvalue0, err18 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err18 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetDealerBail(value0))
		fmt.Print("\n")
		break
	case "freezeBail":
		if flag.NArg()-1 != 3 {
			fmt.Fprintln(os.Stderr, "FreezeBail requires 3 args")
			flag.Usage()
		}
		argvalue0, err19 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err19 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		argvalue1, err20 := (strconv.ParseFloat(flag.Arg(2), 64))
		if err20 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		argvalue2, err21 := (strconv.ParseInt(flag.Arg(3), 10, 64))
		if err21 != nil {
			Usage()
			return
		}
		value2 := argvalue2
		fmt.Print(client.FreezeBail(value0, value1, value2))
		fmt.Print("\n")
		break
	case "unfreezeBail":
		if flag.NArg()-1 != 2 {
			fmt.Fprintln(os.Stderr, "UnfreezeBail requires 2 args")
			flag.Usage()
		}
		argvalue0, err22 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err22 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		argvalue1, err23 := (strconv.ParseInt(flag.Arg(2), 10, 64))
		if err23 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		fmt.Print(client.UnfreezeBail(value0, value1))
		fmt.Print("\n")
		break
	case "decBail":
		if flag.NArg()-1 != 8 {
			fmt.Fprintln(os.Stderr, "DecBail requires 8 args")
			flag.Usage()
		}
		argvalue0, err24 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err24 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		argvalue1, err25 := (strconv.ParseFloat(flag.Arg(2), 64))
		if err25 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		tmp2, err26 := (strconv.Atoi(flag.Arg(3)))
		if err26 != nil {
			Usage()
			return
		}
		argvalue2 := int32(tmp2)
		value2 := argvalue2
		argvalue3 := flag.Arg(4)
		value3 := argvalue3
		argvalue4, err28 := (strconv.ParseInt(flag.Arg(5), 10, 64))
		if err28 != nil {
			Usage()
			return
		}
		value4 := argvalue4
		tmp5, err29 := (strconv.Atoi(flag.Arg(6)))
		if err29 != nil {
			Usage()
			return
		}
		argvalue5 := int32(tmp5)
		value5 := argvalue5
		argvalue6, err30 := (strconv.ParseInt(flag.Arg(7), 10, 64))
		if err30 != nil {
			Usage()
			return
		}
		value6 := argvalue6
		argvalue7, err31 := (strconv.ParseInt(flag.Arg(8), 10, 64))
		if err31 != nil {
			Usage()
			return
		}
		value7 := argvalue7
		fmt.Print(client.DecBail(value0, value1, value2, value3, value4, value5, value6, value7))
		fmt.Print("\n")
		break
	case "incBail":
		if flag.NArg()-1 != 7 {
			fmt.Fprintln(os.Stderr, "IncBail requires 7 args")
			flag.Usage()
		}
		argvalue0, err32 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err32 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		argvalue1, err33 := (strconv.ParseFloat(flag.Arg(2), 64))
		if err33 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		argvalue3 := flag.Arg(4)
		value3 := argvalue3
		argvalue4, err36 := (strconv.ParseInt(flag.Arg(5), 10, 64))
		if err36 != nil {
			Usage()
			return
		}
		value4 := argvalue4
		tmp5, err37 := (strconv.Atoi(flag.Arg(6)))
		if err37 != nil {
			Usage()
			return
		}
		argvalue5 := int32(tmp5)
		value5 := argvalue5
		tmp6, err38 := (strconv.Atoi(flag.Arg(7)))
		if err38 != nil {
			Usage()
			return
		}
		argvalue6 := int32(tmp6)
		value6 := argvalue6
		fmt.Print(client.IncBail(value0, value1, value2, value3, value4, value5, value6))
		fmt.Print("\n")
		break
	case "unfreezeDecBail":
		if flag.NArg()-1 != 5 {
			fmt.Fprintln(os.Stderr, "UnfreezeDecBail requires 5 args")
			flag.Usage()
		}
		argvalue0, err39 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err39 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		argvalue1, err40 := (strconv.ParseInt(flag.Arg(2), 10, 64))
		if err40 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		argvalue2, err41 := (strconv.ParseFloat(flag.Arg(3), 64))
		if err41 != nil {
			Usage()
			return
		}
		value2 := argvalue2
		tmp3, err42 := (strconv.Atoi(flag.Arg(4)))
		if err42 != nil {
			Usage()
			return
		}
		argvalue3 := int32(tmp3)
		value3 := argvalue3
		argvalue4 := flag.Arg(5)
		value4 := argvalue4
		fmt.Print(client.UnfreezeDecBail(value0, value1, value2, value3, value4))
		fmt.Print("\n")
		break
	case "getBailLogsByDealerId":
		if flag.NArg()-1 != 7 {
			fmt.Fprintln(os.Stderr, "GetBailLogsByDealerId requires 7 args")
			flag.Usage()
		}
		argvalue0, err44 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err44 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		tmp1, err45 := (strconv.Atoi(flag.Arg(2)))
		if err45 != nil {
			Usage()
			return
		}
		argvalue1 := int32(tmp1)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		tmp3, err47 := (strconv.Atoi(flag.Arg(4)))
		if err47 != nil {
			Usage()
			return
		}
		argvalue3 := int32(tmp3)
		value3 := argvalue3
		tmp4, err48 := (strconv.Atoi(flag.Arg(5)))
		if err48 != nil {
			Usage()
			return
		}
		argvalue4 := int32(tmp4)
		value4 := argvalue4
		tmp5, err49 := (strconv.Atoi(flag.Arg(6)))
		if err49 != nil {
			Usage()
			return
		}
		argvalue5 := int32(tmp5)
		value5 := argvalue5
		tmp6, err50 := (strconv.Atoi(flag.Arg(7)))
		if err50 != nil {
			Usage()
			return
		}
		argvalue6 := int32(tmp6)
		value6 := argvalue6
		fmt.Print(client.GetBailLogsByDealerId(value0, value1, value2, value3, value4, value5, value6))
		fmt.Print("\n")
		break
	case "":
		Usage()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
	}
}
